### ISSUE TITLE
Handle multiple signing secrets

### ISSUE THREAD

**Issue by cjavilla-stripe** [cecilphillip-stripe/stripe-dotnet-extensions#4]
I'd love to see us support multiple webhook signing secrets either as part of the webhook processing extension or the Stripe.net SDK directly. When working with Connect, users will have at least 2 webhook endpoints set up, each with a unique secret. In the past, we've told users to "try" checking one signature and if that raises an exception "try" the next secret.

Ideally we could do that try/catch logic for devs and not use exception handling for control flow.

**Comment by cecilphillip** [comment]
Added Keyed registrations
